name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Are you sure you want to deploy to production?'
        required: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm clean-install --no-audit --prefer-offline || npm install --no-audit --prefer-offline
          npm ls --depth=0
        
      - name: Run linting
        run: |
          npm run lint
          npm run lint:md
          
      - name: Run tests
        run: npm test
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
      - name: Update production branch
        run: |
          git checkout production
          git merge main --no-ff -m "chore: merge main into production for deployment"
          git push origin production 